name: model-env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy=1.21.2
  - pip=21.2.4
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - numpy
  - pandas
  - pip:
    - azureml-defaults==1.47.0
    - applicationinsights
    - inference-schema[numpy-support]==1.5
    - joblib==1.0.1
